name: "Common Setup"

inputs:
  OP_SERVICE_ACCOUNT_TOKEN:
    required: true
  CACHE:
    default: "public"
  TAILSCALE:
    default: ""
  REMOTE_BUILDERS:
    default: ""
  SYSTEM:
    default: ""

outputs:
  GITHUB_ACCESS_TOKEN:
    value: "${{ steps.secrets.outputs.GITHUB_ACCESS_TOKEN }}"
  CACHE_BUCKET:
    value: "${{ steps.secrets.outputs.CACHE_BUCKET }}"
  CACHE_SECRET_KEY:
    value: "${{ steps.secrets.outputs.CACHE_SECRET_KEY }}"
  CACHE_AWS_ACCESS_KEY_ID:
    value: "${{ steps.secrets.outputs.CACHE_AWS_ACCESS_KEY_ID }}"
  CACHE_AWS_SECRET_ACCESS_KEY:
    value: "${{ steps.secrets.outputs.CACHE_AWS_SECRET_ACCESS_KEY }}"
  SSH_KEY:
    value: "${{ steps.secrets.outputs.SSH_KEY }}"
  TAILSCALE_URL:
    value: "${{ steps.secrets.outputs.TAILSCALE_URL }}"
  TAILSCALE_AUTH_KEY:
    value: "${{ steps.secrets.outputs.TAILSCALE_AUTH_KEY }}"
  REMOTE_BUILDERS:
    value: "${{ steps.secrets.outputs.REMOTE_BUILDERS }}"
  AUTH0_FLOX_DEV_CLIENT_SECRET:
    value: "${{ steps.secrets.outputs.AUTH0_FLOX_DEV_CLIENT_SECRET }}"

runs:
  using: "composite"
  steps:
    - name: "Load secrets"
      id: "secrets"
      uses: "1password/load-secrets-action@v2"
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: "${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}"
        GITHUB_ACCESS_TOKEN: "op://github-actions/ci/floxbot-github-access-token"
        CACHE_BUCKET: "${{ format('op://github-actions/flox-cache-{0}/s3-bucket', inputs.CACHE) }}"
        CACHE_SECRET_KEY: "${{ format('op://github-actions/flox-cache-{0}/secret-key', inputs.CACHE) }}"
        CACHE_AWS_ACCESS_KEY_ID: "${{ format('op://github-actions/flox-cache-{0}/aws-access-key', inputs.CACHE) }}"
        CACHE_AWS_SECRET_ACCESS_KEY: "${{ format('op://github-actions/flox-cache-{0}/aws-secret-access-key', inputs.CACHE) }}"
        SSH_KEY: "op://github-actions/ci/floxbot-ssh-key"
        TAILSCALE_URL: "op://github-actions/ci/tailscale-url"
        TAILSCALE_AUTH_KEY: "op://github-actions/ci/tailscale-auth-key"
        REMOTE_BUILDERS: "op://github-actions/ci/remote-builders"
        AUTH0_FLOX_DEV_CLIENT_SECRET: "op://github-actions/ci/auth0-flox-dev-client-secret"

    - name: "Setup Tailscale"
      uses: "tailscale/github-action@v2"
      if: ${{ inputs.TAILSCALE }}
      with:
        args: "--timeout 30s --login-server ${{ steps.secrets.outputs.TAILSCALE_URL }}"
        tags: "tag:ci"
        authkey: "${{ steps.secrets.outputs.TAILSCALE_AUTH_KEY }}"

    - name: "Install newer Nix"
      uses: "cachix/install-nix-action@v24"

    - name: "Install flox"
      uses: "flox/install-flox-action@main"
      with:
        github-access-token:    "${{ steps.secrets.outputs.GITHUB_ACCESS_TOKEN }}"
        substituter:            "${{ steps.secrets.outputs.CACHE_BUCKET }}"
        substituter-key:        "${{ steps.secrets.outputs.CACHE_SECRET_KEY }}"
        aws-access-key-id:      "${{ steps.secrets.outputs.CACHE_AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key:  "${{ steps.secrets.outputs.CACHE_AWS_SECRET_ACCESS_KEY }}"
        ssh-key:                "${{ steps.secrets.outputs.SSH_KEY }}"
        remote-builders:        "${{ inputs.REMOTE_BUILDERS && steps.secrets.outputs.REMOTE_BUILDERS || '' }}"

    - name: "Configure Nix"
      shell: "bash"
      run: |
        sudo echo
        {
          echo "experimental-features = nix-command flakes";
          echo "accept-flake-config = true";
        } | sudo tee -a /etc/nix/nix.conf >/dev/null

    - name: "Find remote server to run tests on"
      if: ${{ inputs.SYSTEM }}
      shell: "bash"
      run: |
        set -eo pipefail
        export REMOTE_SERVER=$(cat /etc/nix/machines | grep ${{ inputs.SYSTEM }} | cut -f1 -d' ' | cut -f3 -d'/' | head -1 | sed 's/nixbld@//' ; )
        export REMOTE_SERVER_USER_KNOWN_HOSTS_FILE=$(mktemp)
        export REMOTE_PUBLIC_HOST_KEY=$(cat /etc/nix/machines | grep ${{ inputs.SYSTEM }} | tr -s ' ' | cut -f8 -d' ' | base64 -d ; )
        printf "%s %s\n" "$REMOTE_SERVER" "$REMOTE_PUBLIC_HOST_KEY" > "$REMOTE_SERVER_USER_KNOWN_HOSTS_FILE"
        echo "REMOTE_SERVER: $REMOTE_SERVER"
        echo "REMOTE_SERVER_USER_KNOWN_HOSTS_FILE: $REMOTE_SERVER_USER_KNOWN_HOSTS_FILE"
        cat $REMOTE_SERVER_USER_KNOWN_HOSTS_FILE
        echo "REMOTE_SERVER=$REMOTE_SERVER" >> $GITHUB_ENV
        echo "REMOTE_SERVER_USER_KNOWN_HOSTS_FILE=$REMOTE_SERVER_USER_KNOWN_HOSTS_FILE" >> $GITHUB_ENV
