#!/usr/bin/env bash
set -euo pipefail

NESTING="$1"
echo "${NESTING} FLOX_ACTIVATE_START_SERVICES=${FLOX_ACTIVATE_START_SERVICES}"
echo "${NESTING} _FLOX_SERVICES_TO_START=${_FLOX_SERVICES_TO_START:-unset}"
