# Activate a project environment using --dir

set dir [lindex $argv 0]
set flox $env(FLOX_BIN)
set timeout 10
set env(NO_COLOR) 1
set env(TERM) xterm-mono
set stty_init "cols 1000"

spawn $flox activate --dir $dir
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

expect "You are now using the environment"
expect $env(KNOWN_PROMPT)

send "exit\n"
expect eof
