# Activate a project environment using --dir and check
# - hello is installed
# - prompt is set
# Assume throughout that the project is named project-\d+

set dir [lindex $argv 0]
set flox $env(FLOX_BIN)

expect_before {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
}

spawn $flox activate --dir $dir
expect -ex "Building environment..." {}
expect -re "flox .*\\\[project-\\d+\\\]" {}

# check for hello
send "{ command -v hello||which hello||type -P hello; } 2>&1\n"
expect -re "project-\\d+/\.flox/run/.*\.project-\\d+/bin/hello" {}

# check for hello after changing directory
send "cd ..\n"
send "{ command -v hello||which hello||type -P hello; } 2>&1\n"
expect -re "project-\\d+/\.flox/run/.*\.project-\\d+/bin/hello" {}

send "exit\n"
expect eof
