# Activate a project environment using --dir and check
# - hello is installed
# - prompt is set ### XXX how exactly? I don't see it doing this.
# Assume throughout that the project is named project-\d+

set dir [lindex $argv 0]
set flox $env(FLOX_BIN)

set timeout 20

spawn $flox -v activate --dir $dir
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}
expect "Preparing environment"

# check for hello
send "command -v hello||which hello||type -P hello || echo not found\n"

# check for hello after changing directory
send "cd ..\n"
send "command -v hello||which hello||type -P hello || echo not found\n"

send "exit\n"
expect eof
