# Activate a project environment using --dir and check
# - hello is installed
# - prompt is set
# Assume throughout that the project is named project-\d+

set dir [lindex $argv 0]
set flox $env(FLOX_BIN)
set env(NO_COLOR) 1
set env(TERM) xterm-mono
set stty_init "cols 1000"

set timeout 20
exp_internal 1

spawn $flox activate --dir $dir
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

# check that prompt is set for interactive shell
expect {flox \[project-*\]}

# check for hello
send "command -v hello||which hello||type -P hello || echo not found\n"

# check for hello after changing directory
send "cd ..\n"
send "command -v hello||which hello||type -P hello || echo not found\n"

send "exit\n"
expect eof
