# Test 'flox edit' prompts user to re-activate

set manifest [lindex $argv 0]
set flox $env(FLOX_BIN)

# activate environment 1
set timeout 10
# activate environment 1
spawn $flox activate
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
}

# edit environment and check for message prompting to re-activate
send "$flox edit -f $manifest\n"
expect -ex "Your manifest has changes that cannot be automatically applied to your current environment.\r\n\r\nPlease `exit` the environment and run `flox activate` to see these changes." {}

send "exit\n"
expect eof
