#! /usr/bin/env bats
# -*- mode: bats; -*-
# ============================================================================ #
#
# Test the `flox build' subcommand.
#
# ---------------------------------------------------------------------------- #

load test_support.bash

# bats file_tags=build

# ---------------------------------------------------------------------------- #

setup_file() {
  common_file_setup
}

# ---------------------------------------------------------------------------- #

project_setup() {
  export PROJECT_DIR="${BATS_TEST_TMPDIR?}/project-${BATS_TEST_NUMBER?}"
  export PROJECT_NAME="${PROJECT_DIR##*/}"

  rm -rf "$PROJECT_DIR"
  mkdir -p "$PROJECT_DIR"
  pushd "$PROJECT_DIR" > /dev/null || return

  "$FLOX_BIN" init -d "$PROJECT_DIR"

  git -C "$PROJECT_DIR" init -q
  git -C "$PROJECT_DIR" config user.name "test"
  git -C "$PROJECT_DIR" config user.email "test@email.address"
}

project_teardown() {
  popd > /dev/null || return
  rm -rf "${PROJECT_DIR?}"
  unset PROJECT_DIR
  unset PROJECT_NAME
}

# Replace the environment with the pre-locked `hello` fixture, so the project
# has a locked package set without any catalog resolution happening here. That
# package set is what used to supply the nixpkgs for expression builds. The
# fixture pins all four systems, so no test in this file may skip on
# x86_64-darwin.
hello_env_setup() {
  cp "$GENERATED_DATA"/envs/hello/manifest.toml \
    "$GENERATED_DATA"/envs/hello/manifest.lock \
    "$PROJECT_DIR/.flox/env/"
}

# The nixpkgs revision the environment fixture is locked to, read from the
# fixture rather than copied into this file: `just md -f` re-records it against
# production and a stale literal here would look like a product bug.
toplevel_locked_rev() {
  jq -r '[.packages[] | select(.group == "toplevel")][0].rev' \
    "$GENERATED_DATA/envs/hello/manifest.lock"
}

# The revision the base-catalog cassette serves as the newest `stable` page,
# read from the cassette for the same reason. Regenerated by
# `just gen-unit-data-for-publish` against a local FloxHub.
catalog_stable_rev() {
  yq -r '.then.body' "$UNIT_TEST_GENERATED/get_base_catalog_nixpkgs_url.yaml" \
    | jq -r '[.scraped_pages[] | select(.stability_tags[] == "stable")][0].rev'
}

# Add a git-tracked Nix expression package. It depends only on plain nixpkgs,
# so no catalog inputs are locked.
nef_package_setup() {
  local name="${1?}"
  local pkg_dir="$PROJECT_DIR/.flox/pkgs/$name"
  mkdir -p "$pkg_dir"
  cat > "$pkg_dir/default.nix" << 'EOF'
{stdenv, hello}:
stdenv.mkDerivation {
  pname = "PNAME_PLACEHOLDER";
  version = "1.0";
  src = ./.;
  buildInputs = [ hello ];
  installPhase = "mkdir -p $out; echo hi > $out/hi";
}
EOF
  sed -i.bak "s/PNAME_PLACEHOLDER/$name/" "$pkg_dir/default.nix"
  rm -f "$pkg_dir/default.nix.bak"
  git -C "$PROJECT_DIR" add -A
  git -C "$PROJECT_DIR" commit -q -m "add $name"
}

# Add a manifest build to a project with no packages installed, so the edit
# needs no resolution and the environment stays locked as `flox init` left it.
manifest_build_only_setup() {
  "$FLOX_BIN" edit -d "$PROJECT_DIR" -f - << 'EOF'
version = 1

[build.shout]
command = "mkdir -p $out; echo shout > $out/shout"
EOF
}

# Add a manifest build alongside whatever else the project defines, keeping the
# fixture's `[install]` so the environment stays locked as recorded.
manifest_build_setup() {
  "$FLOX_BIN" edit -d "$PROJECT_DIR" -f - << 'EOF'
version = 1

[install]
hello.pkg-path = "hello"

[build.shout]
command = "mkdir -p $out; echo shout > $out/shout"
EOF
  git -C "$PROJECT_DIR" add -A
  git -C "$PROJECT_DIR" commit -q -m "add a manifest build"
}

# ---------------------------------------------------------------------------- #

setup() {
  common_test_setup
  home_setup test # Isolate $HOME for each test.
  setup_isolated_flox
  export _FLOX_USE_CATALOG_MOCK="$GENERATED_DATA/empty.yaml"
}

teardown() {
  if [ -n "${PROJECT_DIR:-}" ]; then
    project_teardown
  fi
  common_test_teardown
}

# ---------------------------------------------------------------------------- #
# Which nixpkgs a Nix expression build resolves against.
#
# The environment's locked package set used to decide this, which pinned every
# expression build to whatever revision the environment last resolved. The
# catalog server decides it now, so these tests mock the base-catalog-info
# endpoint rather than the generic empty fixture used elsewhere.

# bats test_tags=build:nixpkgs
@test "build: expression build resolves the catalog's nixpkgs, not the environment's" {
  project_setup
  hello_env_setup
  nef_package_setup greet
  export _FLOX_USE_CATALOG_MOCK="$UNIT_TEST_GENERATED/get_base_catalog_nixpkgs_url.yaml"

  run "$FLOX_BIN" build -d "$PROJECT_DIR" greet
  assert_success

  # Assert on the build, not on what the build said. The environment locks a
  # `hello` from its own revision; the expression build must not consume it.
  local env_hello
  env_hello="$(jq -r \
    '[.packages[] | select(.install_id == "hello" and .system == env.NIX_SYSTEM)][0].outputs.out' \
    "$PROJECT_DIR/.flox/env/manifest.lock")"
  refute [ -z "$env_hello" ]

  run nix derivation show -r "$PROJECT_DIR/result-greet"
  assert_success
  refute_output --partial "$env_hello"

  # And the revision it reports is the catalog's, not the environment's.
  run "$FLOX_BIN" build -d "$PROJECT_DIR" greet
  assert_success
  assert_output --partial "$(catalog_stable_rev | cut -c1-7)"
  refute_output --partial "$(toplevel_locked_rev | cut -c1-7)"
}

# bats test_tags=build:nixpkgs
@test "build: warns when manifest and expression builds use different nixpkgs" {
  project_setup
  hello_env_setup
  nef_package_setup greet
  manifest_build_setup
  export _FLOX_USE_CATALOG_MOCK="$UNIT_TEST_GENERATED/get_base_catalog_nixpkgs_url.yaml"

  run "$FLOX_BIN" build -d "$PROJECT_DIR" shout
  assert_success
  assert_output --partial "different nixpkgs revisions"
  assert_line --partial "manifest builds:        nixpkgs rev $(toplevel_locked_rev | cut -c1-7)"
  assert_line --partial "Nix expression builds:  nixpkgs rev $(catalog_stable_rev | cut -c1-7)"
  assert_output --partial "flox upgrade"
}

# bats test_tags=build:nixpkgs
@test "build: manifest-only project never contacts the base catalog" {
  project_setup
  manifest_build_only_setup

  # The empty fixture answers no base-catalog-info request, so a build that
  # made one would fail here rather than succeed.
  run "$FLOX_BIN" build -d "$PROJECT_DIR" shout
  assert_success
  refute_output --partial "Nix expression builds use nixpkgs"
}

# bats test_tags=build:nixpkgs
@test "build: an unreachable catalog names the way past it" {
  project_setup
  hello_env_setup
  nef_package_setup greet

  # The empty fixture cannot answer the base-catalog-info request an
  # expression build needs, which is the shape of an offline build.
  run "$FLOX_BIN" build -d "$PROJECT_DIR" greet
  assert_failure
  assert_output --partial "Could not get information about the base catalog."
  assert_output --partial "--nixpkgs-url"
}

# The remedy the failure above names has to work in the project that hits it,
# including when a manifest build is what was asked for: a manifest build in a
# project that also has expressions still resolves a nixpkgs for them.
# bats test_tags=build:nixpkgs
@test "build: --nixpkgs-url builds a manifest target in a project with expressions" {
  project_setup
  hello_env_setup
  nef_package_setup greet
  manifest_build_setup

  run "$FLOX_BIN" build -d "$PROJECT_DIR" \
    --nixpkgs-url "https://github.com/flox/nixpkgs?rev=$(catalog_stable_rev)" shout
  assert_success
  assert_output --partial "Built output"
}
