echo "sourcing .bashrc"
# echo "sourcing: ${_flox_sourcing_rc:-empty}"
# echo "sourced: ${_flox_sourced_rc:-empty}"
export PS1="myprompt>"
eval "$(/Users/zmitchell/src/flox/double-bashrc-exec/cli/target/debug/flox activate -m run -d "$PWD")"
