#! /usr/bin/env bash
# ============================================================================ #
#
# Wraps the `iwyu_tool.py'/`include-what-you-use' executable our settings
# and options.
#
#
# ---------------------------------------------------------------------------- #

set -eu;
set -o pipefail;


# ---------------------------------------------------------------------------- #

_as_me="iwyu";

_version="0.2.0";

_usage_msg="USAGE: $_as_me [OPTIONS...] [PROJECT-ROOT:=\$PWD] -- \
[EXTRA-IWYU-ARGS...]

Runs \`iwyu_tool.py' with our settings and options.
";

_help_msg="$_usage_msg
This explicitly adds the \`-Xiwyu' option to all \`EXTRA-IWYU-ARGS' for
convenience.

A mapping file \`build-aux/iwyu-mappings.json' is automatically applied.

Setting any \`EXTRA-IWYU-ARGS' will override the defaults.
The default \`EXTRA-IWYU-ARGS' are:
  -Xiwyu --no_comments

OPTIONS
  -t,--tool-opt OPT   Pass an option(s) to \`iwyu_tool.py'
  -f,--file PATH      Target specific file(s). May be used multiple times.
  -V,--verbose        Run in verbose mode.
  -h,--help           Print help message to STDOUT.
  -u,--usage          Print usage message to STDOUT.
  -v,--version        Print version information to STDOUT.

ENVIRONMENT
  IWYU_TOOL           Command used as \`iwyu_tool.py' executable.
  FIND                Command used as \`find' executable.
  MAKE                Command used as \`make' executable.
";


# ---------------------------------------------------------------------------- #

usage() {
  if [[ "${1:-}" = "-f" ]]; then
    echo "$_help_msg";
  else
    echo "$_usage_msg";
  fi
}


# ---------------------------------------------------------------------------- #

# @BEGIN_INJECT_UTILS@
: "${FIND:=find}";
: "${IWYU_TOOL:=iwyu_tool.py}";
: "${MAKE:=make}";


# ---------------------------------------------------------------------------- #

_VERBOSE='';
_PROJECT_ROOT='';
declare -a _SOURCES;
_SOURCES=();
declare -a _iwyu_args;
_iwyu_args=();

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    # Split short options such as `-abc' -> `-a -b -c'
    -[^-]?*)
      _arg="$1";
      declare -a _args;
      _args=();
      shift;
      _i=1;
      while [[ "$_i" -lt "${#_arg}" ]]; do
        _args+=( "-${_arg:$_i:1}" );
        _i="$(( _i + 1 ))";
      done
      set -- "${_args[@]}" "$@";
      unset _arg _args _i;
      continue;
    ;;
    --*=*)
      _arg="$1";
      shift;
      set -- "${_arg%%=*}" "${_arg#*=}" "$@";
      unset _arg;
      continue;
    ;;
    -t|--tool-opt)
      shift;
      if [[ "$#" -lt 1 ]]; then
        echo "$_as_me: Missing argument to \`--tool-opt OPT' option" >&2;
        usage -f;
        exit 1;
      fi
      # Unquote
      eval "_iwyu_args+=( $1 )";
    ;;
    -f|--file)
      shift;
      if [[ "$#" -lt 1 ]]; then
        echo "$_as_me: Missing argument to \`--file PATH' option" >&2;
        usage -f;
        exit 1;
      fi
      if ! [[ -f "$1" ]]; then
        echo "$_as_me: No such file \`--file $1'" >&2;
        exit 1;
      fi
      if ! [[ -r "$1" ]]; then
        echo "$_as_me: Unable to read \`--file $1'" >&2;
        exit 1;
      fi
      _SOURCES+=( "$1" );
    ;;
    -V|--verbose)  _VERBOSE=:; ;;
    -u|--usage)    usage;    exit 0; ;;
    -h|--help)     usage -f; exit 0; ;;
    -v|--version)  echo "$_version"; exit 0; ;;
    --) shift; break; ;;
    -?|--*)
      echo "$_as_me: Unrecognized option: \`$1'" >&2;
      usage -f >&2;
      exit 1;
    ;;
    *)
      if [[ -z "$_PROJECT_ROOT" ]]; then
        _PROJECT_ROOT="$1";
      else
        echo "$_as_me: Unexpected argument(s) \`$*'" >&2;
        usage -f >&2;
        exit 1;
      fi
    ;;
  esac
  shift;
done


# ---------------------------------------------------------------------------- #

# Set fallbacks.

: "${_PROJECT_ROOT:=$PWD}";


# ---------------------------------------------------------------------------- #

# Any remaining args go into `_extra_iwyu_args'.
declare -a _extra_iwyu_args;
if [[ "$#" -gt 0 ]]; then
  _extra_iwyu_args+=( "$@" );
else
  _extra_iwyu_args+=( --no_comments );
fi


# ---------------------------------------------------------------------------- #

# Validate args
if ! [[ -d "$_PROJECT_ROOT" ]]; then
  echo "$_as_me: No such directory: \`$_PROJECT_ROOT'" >&2;
  exit 1;
fi


# ---------------------------------------------------------------------------- #

# Create `compile_commands.json' if it's missing.
if ! [[ -r "$_PROJECT_ROOT/compile_commands.json" ]]; then
  $MAKE -C "$_PROJECT_ROOT" compile_commands.json;
fi


# ---------------------------------------------------------------------------- #

# Generate arguments for \`iwyu_tool.py':

_iwyu_args+=( -p "$_PROJECT_ROOT" );

# Add target file args for `iwyu_tool.py' if they were given.
if [[ "${#_SOURCES[@]}" -gt 0 ]]; then _iwyu_args+=( "${_SOURCES[@]}" ); fi

# Add `--' separator to begin args for underlying `include-what-you-use' util.
_iwyu_args+=(
  --
  -Xiwyu --mapping_file="$_PROJECT_ROOT/build-aux/iwyu-mappings.json"
);

# Add \`-Xiwyu' to all \`_extra_iwyu_args'.
for _arg in "${_extra_iwyu_args[@]}"; do
  if [[ -n "$_arg" ]]; then
    _iwyu_args+=( -Xiwyu "$_arg" );
  fi
done


# ---------------------------------------------------------------------------- #

# Runnit!

# Log command if we're in verbose mode.
if [[ -n "${_VERBOSE:-}" ]]; then echo "$IWYU_TOOL ${_iwyu_args[*]}" >&2; fi

$IWYU_TOOL "${_iwyu_args[@]}";


# ---------------------------------------------------------------------------- #
#
#
#
# ============================================================================ #
