# Activate a project environment using --dir and check
# - hello is installed
# - prompt is set
# Assume throughout that the project is named project-\d+

set dir [lindex $argv 0]
set flox $env(FLOX_CLI)

set cmd "$flox activate --dir $dir"
spawn $flox activate --dir $dir
expect {
    "Building environment..." {}
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}
set timeout 60
expect {
    -re "project.*\$" {}
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}

# activation is the only thing that should take very long so set a low timeout
set timeout 1

# check for hello
send "{ command -v hello||which hello||type -P hello; } 2>&1\n"
expect {
    -re "project-\\d+/\.flox/run/.*\.project-\\d+/bin/hello" {}
    timeout {
      puts stderr "Reached timeout locating 'hello'"
      exit 1
    }
}

expect {
    # TODO check prompt colors
    -re "flox .*\\\[project-\\d+\\\]" {}
    timeout {
      puts stderr "Reached timeout checking prompt"
      exit 1
    }
}

exit 0
