# Activate a project environment using --dir and check an environment variable
# is set.

set dir [lindex $argv 0]
set flox $env(FLOX_CLI)

set cmd "$flox activate --dir $dir"
spawn $flox activate --dir $dir
expect {
    "Building environment..." {}
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}
set timeout 20
expect {
    -re "project.*\$" {}
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}

# activation is the only thing that should take very long so set a low timeout
set timeout 1

# check for alias
send "echo \$foo\n"
expect {
    "baz" {}
    timeout {
      puts stderr "Reached timeout checking for test_alias"
      exit 1
    }
}

exit 0
