# Activate a project environment using --dir and check the environment's hook is
# run.

set dir [lindex $argv 0]
set flox $env(FLOX_CLI)

set timeout 5
set cmd "$flox activate --dir $dir"
spawn $flox activate --dir $dir
expect {
    "Building environment..." {}
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}
expect {
    "Welcome to your flox environment!" {}
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}

exit 0
