# Package-specific defaults here.
# Company-specific defaults in /etc/flox.toml.
# User-specific overrides in ~/.config/flox/flox.toml.

# TODO: change to "https://meta.flox.dev/" or similar, stop relying on ssh.
git_base_url = "https://git.saas.floxdev.com/"
