# Test that LD_AUDIT and ld-floxlib.so works as expected on Linux only.
#
# This test loads up a flox environment containing the following packages as
# installed by tests/ld-floxlib.bats:
# * gcc-wrapped (to be able to compile the test program)
# * a pinned version of glibc from the past
# * giflib (a package that is presumed to be not available by default)
#
# It then activates the env to perform two distinct tests:
# 1: load libraries found in $FLOX_ENV_LIBS last
#   - compile the get-glibc-version program (with LIBRARY_PATH=$FLOX_ENV_LIBS)
#   - run it with no environment (using `env -i`) to observe the default
#     glibc version and confirm this does NOT match the pinned version
#   - repeat with LD_AUDIT defined and confirm that the version again does
#     not change
#   - repeat with LD_LIBRARY_PATH=$FLOX_ENV_LIBS and confirm that the
#     version does change
# 2: confirm LD_AUDIT can find missing libraries
#   - compile the print-gif-info program
#   - observe that it can run the compiled program on the sample gif
#   - unset LD_AUDIT and confirm it cannot run the program

# exp_internal 1
set flox $env(FLOX_BIN)

spawn $flox activate
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
}

expect -ex "Building environment" {}

# All these commands run pretty quick.
set timeout 3

### Verify environment

# FLOX_ENV_LIBS is defined
send "{ text -n FLOX_ENV_LIBS && echo FLOX_ENV_LIBS_CONFIRMED_NONEMPTY; } 2>&1\n"
expect -ex "FLOX_ENV_LIBS_CONFIRMED_NONEMPTY" {}

# LD_AUDIT is defined and points to ld-floxlib.so
send "{ echo $LD_AUDIT; } 2>&1\n"
expect -ex "/ld-floxlib.so" {}

# LD_LIBRARY_PATH is not defined
send "{ test -z LD_LIBRARY_PATH && echo LD_LIBRARY_PATH_CONFIRMED_EMPTY; } 2>&1\n"
expect -ex "LD_LIBRARY_PATH_CONFIRMED_EMPTY" {}


### Test 1: load libraries found in $FLOX_ENV_LIBS last

send "{ cc -o get-glibc-version ./get-glibc-version.c && echo compilation done; } 2>&1\n"
expect -ex "compilation done" {}

send "{ ./get-glibc-version; } 2>&1\n"
expect -ex "GNU C Library (glibc) version: " {}

# TODO: exercise LD_LIBRARY_PATH and LD_AUDIT to get different results.


### Test 2: confirm LD_AUDIT can find missing libraries

send "{ cc -o print-gif-info ./print-gif-info.c -lgif && echo compilation done; } 2>&1\n"
expect -ex "compilation done" {}

send "{ ./print-gif-info ./flox-edge.gif; } 2>&1\n"
expect -ex "GIF Information for: ./flox-edge.gif
expect -ex "Number of frames: 0
expect -ex "Width: 270 pixels
expect -ex "Height: 137 pixels

send "exit\n"
expect eof
