# Activate a project environment and check
# - pip and python3 are installed
# -
# Assume throughout that the project is named project-\d+

set flox $env(FLOX_BIN)

spawn $flox activate
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
}

expect -ex "Preparing environment" {}

set timeout 300
send "{ command -v python3||which python3||type -P python3; } 2>&1\n"
expect -re "\.flox/run/\[^\n\r\]*\.project-\\d+/bin/python3" {}

set timeout 10
send "{ command -v python3||which python3||type -P python3; } 2>&1\n"
send "{ command -v pip||which pip||type -P pip; } 2>&1\n"
expect -re "\.flox/run/\[^\n\r\]*\.project-\\d+/bin/pip" {}

send "cat \$PIP_CONFIG_FILE\n"
expect -ex "require-virtualenv = true" {}

set timeout 30
send "pip install requests\n"
expect -ex "ERROR: Could not find an activated virtualenv" {}

send "python3 -m venv env\n"
expect -re "flox \[^\n\r\]*\\\[project-\\d+\\\]" {}

# create python virtualenv
send "./env/bin/pip install requests\n"
expect -ex "Collecting requests" {}
expect -ex "Installing collected packages" {}
expect -ex "Successfully installed" {}

# test requests library in python
set timeout 10
send "./env/bin/python -c 'import requests; print(requests.__path__)'\n"
expect -re "\\\['.*/project-\\d+/env/lib/python\\d+.\\d+/site-packages/requests'\\\]" {}

send "exit\n"
expect eof
