# A lock was generated for this manifest with
# flox init
# OUTPUT_DIRNAME=python2_insecure
# cp "./test_data/manually_generated/$OUTPUT_DIRNAME/manifest.toml" .flox/env/manifest.toml
# FLOX_FEATURES_USE_CATALOG=false flox list
# cp .flox/env/manifest.lock "test_data/manually_generated/$OUTPUT_DIRNAME/manifest.lock"

[install]
python2.pkg-path = "python2"

[options]
systems = [ "aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux" ]
