#!/usr/bin/env bash
# shellcheck shell=bash

# Trace levels supported by activation scripts:
#   1. (-v) top-level activate script
#   2. (-vv) language-specific profile scripts
#   3. (-vvv) zsh `autoload -U compinit` (very verbose)
[ "${_flox_activate_tracelevel:?}" -eq 0 ] || set -x

"${_flox_activate_tracer:?}" "${BASH_SOURCE[0]}" "$@" START

_dirname="@coreutils@/bin/dirname"
_getopt="@getopt@/bin/getopt"
_readlink="@coreutils@/bin/readlink"
_flox_activations="@flox_activations@"

set -euo pipefail

# These all derive from the `flox-interpreter` package.
# FIXME This is wrong; the profile.d scripts in particular should be
#       sourced from the environment itself so that users can add pkgs
#       which add additional scripts to the etc/profile.d directory.
export _activate_d="__OUT__/activate.d"
_tcsh_home="__OUT__/activate.d/tcsh_home"
_zdotdir="__OUT__/activate.d/zdotdir"

# shellcheck source-path=SCRIPTDIR/activate.d
source "${_activate_d}/generate-bash-startup-commands.bash"
# shellcheck source-path=SCRIPTDIR/activate.d
source "${_activate_d}/generate-zsh-startup-script.bash"
# shellcheck source-path=SCRIPTDIR/activate.d
source "${_activate_d}/generate-fish-startup-commands.bash"
# shellcheck source-path=SCRIPTDIR/activate.d
source "${_activate_d}/generate-tcsh-startup-commands.bash"
# shellcheck source-path=SCRIPTDIR/activate.d
source "${_activate_d}/helpers.bash"

# Top-level Flox environment activation script.

# Parse command-line arguments.
OPTIONS="e:c:m:"
LONGOPTS="command:,\
shell:,\
env-cache:,\
env-project:,\
env-description:,\
mode:,\
watchdog:,\
noprofile"
USAGE="Usage: $0 [-c \"<cmd> <args>\"] \
[--shell <shell>] \
[--env-cache <path>] \
[--env-project <path>] \
[--env-description <name>] \
[--noprofile] \
[(-m|--mode) (dev|run)] \
[--watchdog <path>]"

if ! PARSED=$("$_getopt" --options="$OPTIONS" --longoptions="$LONGOPTS" --name "$0" -- "$@"); then
  echo "Failed to parse options." >&2
  echo "$USAGE" >&2
  exit 1
fi

# Use eval to remove quotes and replace them with spaces.
eval set -- "$PARSED"

# Set default values for options.
FLOX_CMD=""
FLOX_NOPROFILE="${FLOX_NOPROFILE:-}"
# The rust CLI contains sophisticated logic to detect the shell based on
# $FLOX_SHELL or the process listening on STDOUT, but that won't happen when
# activating from the top-level activation script, so fall back to $SHELL as a
# default.
_FLOX_SHELL="$SHELL"
_FLOX_ENV="$($_dirname -- "${BASH_SOURCE[0]}")"
_FLOX_ENV_ACTIVATION_MODE="dev"
_FLOX_WATCHDOG_BIN=""
while true; do
  case "$1" in
    -c | --command)
      shift
      if [ -z "${1:-}" ]; then
        echo "Option -c requires an argument." >&2
        echo "$USAGE" >&2
        exit 1
      fi
      FLOX_CMD="$1"
      shift
      ;;
    --shell)
      shift
      if [ -z "${1:-}" ]; then
        echo "Option --shell requires a command as an argument." >&2
        echo "$USAGE" >&2
        exit 1
      fi
      _FLOX_SHELL="$1"
      shift
      ;;
    --env-cache)
      shift
      if [ -z "${1:-}" ] || [ ! -d "$1" ]; then
        echo "Option --env-cache requires a valid path as an argument." >&2
        echo "$USAGE" >&2
        exit 1
      fi
      _FLOX_ENV_CACHE="$1"
      shift
      ;;
    --env-project)
      shift
      if [ -z "${1:-}" ] || [ ! -d "$1" ]; then
        echo "Option --env-project requires a valid path as an argument." >&2
        echo "$USAGE" >&2
        exit 1
      fi
      _FLOX_ENV_PROJECT="$1"
      shift
      ;;
    --env-description)
      shift
      if [ -z "${1:-}" ]; then
        echo "Option --env-description requires a name as an argument." >&2
        echo "$USAGE" >&2
        exit 1
      fi
      _FLOX_ENV_DESCRIPTION="$1"
      shift
      ;;
    -m | --mode)
      shift
      if [ -z "${1:-}" ] || ! { [ "$1" == "run" ] || [ "$1" == "dev" ]; }; then
        echo "Option --mode requires 'dev' or 'run' as an argument." >&2
        echo "$USAGE" >&2
        exit 1
      fi
      _FLOX_ENV_ACTIVATION_MODE="$1"
      shift
      ;;
    --watchdog)
      shift
      if [ -z "${1:-}" ] || [ ! -f "$1" ]; then
        echo "Option --watchdog requires a path to the watchdog binary as an argument." >&2
        echo "$USAGE" >&2
        exit 1
      fi
      _FLOX_WATCHDOG_BIN="$1"
      shift
      ;;
    --noprofile)
      FLOX_NOPROFILE="true"
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "Invalid option: $1" >&2
      echo "$USAGE" >&2
      exit 1
      ;;
  esac
done

# Convert the provided command string into an array of arguments in "$@".
# Henceforth in the script it is assumed that these are the arguments to be
# invoked either by this shell (when in build mode) or with the chosen userShell.
if [ -n "$FLOX_CMD" ]; then
  # Throw an error if passed additional arguments along with the -c arg.
  if [ $# -gt 0 ]; then
    echo "Unexpected arguments provided with -c argument: $*" >&2
    echo "$USAGE" >&2
    exit 1
  fi

  # Set $@ to reflect the command to be invoked.
  set -- "$FLOX_CMD"
fi

if [ $# -gt 0 ]; then
  _flox_invocation_type="command"
elif [ -t 1 ] || [ -n "${_FLOX_FORCE_INTERACTIVE:-}" ]; then
  _flox_invocation_type="interactive"
else
  _flox_invocation_type="inplace"
fi

# Respect _FLOX_SHELL_FORCE if set.
declare -r _flox_shell="${_FLOX_SHELL_FORCE:-${_FLOX_SHELL}}"
# Unset FLOX_SHELL to detect the parent shell anew with each flox invocation.
unset FLOX_SHELL

# Bail if the shell is unsupported.
case "$_flox_shell" in
  *bash) ;;
  *fish) ;;
  *tcsh) ;;
  *zsh) ;;
  *)
    echo "Unsupported shell: $_flox_shell" >&2
    exit 1
    ;;
esac

# The CLI is responsible for erroring if the environment is already active.
# We can start-or-attach no matter what

# TODO: we could restore _start_env from the prior activation when performing an ephemeral activation

# sets _FLOX_ATTACH, _FLOX_ACTIVATION_STATE_DIR, _FLOX_ACTIVATION_ID
# Don't eval on one line so that we exit if flox-activations fails
to_eval="$($_flox_activations \
  start-or-attach \
  --runtime-dir "$FLOX_RUNTIME_DIR" \
  --pid "$$" --flox-env "$FLOX_ENV" --store-path "$_FLOX_ACTIVATE_STORE_PATH")"
eval "$to_eval"
export _FLOX_ACTIVATION_STATE_DIR _FLOX_ACTIVATION_ID

# If the current shell is re-activating the same environment then we should only
# re-run profile scripts, without start or attach, because the shell will
# already be attached to an activation.
if [ "$_FLOX_ATTACH" == true ]; then
  # shellcheck source-path=SCRIPTDIR/activate.d
  source "${_activate_d}/attach.bash"
  attach "$_FLOX_ACTIVATION_STATE_DIR" "$_flox_invocation_type"
else
  # shellcheck source-path=SCRIPTDIR/activate.d
  source "${_activate_d}/start.bash"
  start "$_FLOX_ACTIVATION_STATE_DIR" "$_flox_invocation_type"
fi

# Start services before the shell or command is invoked
if [ "${FLOX_ACTIVATE_START_SERVICES:-}" == "true" ]; then
  # shellcheck source-path=SCRIPTDIR/activate.d
  source "${_activate_d}/start-services.bash"
fi

case "${_flox_invocation_type}" in
  command)
    # shellcheck source-path=SCRIPTDIR/activate.d
    source "${_activate_d}/attach-command.bash"
    ;;
  interactive)
    # shellcheck source-path=SCRIPTDIR/activate.d
    source "${_activate_d}/attach-interactive.bash"
    ;;
  inplace)
    # shellcheck source-path=SCRIPTDIR/activate.d
    source "${_activate_d}/attach-inplace.bash"
    ;;
  *)
    echo "Unsupported invocation type: ${_flox_invocation_type}" >&2
    exit 1
    ;;
esac

"$_flox_activate_tracer" "${BASH_SOURCE[0]}" "$@" END
