schema-version = "1.14.0"

[install]
hello.pkg-path = "hello"

[vars]

[hook]

[profile]

[services]

[include]

[build]

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
