# Test 'flox show' prompts when an environment is activated and there is an environment in the current directory

set flox $env(FLOX_BIN)

# activate environment 1
set timeout 20
spawn $flox activate --dir 1
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

expect "?" {} # match any character
send "cd 2\n"
expect "cd 2" {}

# search for hello and expect an interactive prompt
set cmd "$flox show nodejs"
send "$flox show nodejs\n"
expect "Show using which environment?" {}
expect -re "type to filter.*\n"

# choose the first option and expect the corresponding installation
send "\r"
expect -re "nodejs - nodejs@1.*\n" {}
# install hello and check it's installed to environment 2
send "exit\n"
expect eof
