# Test 'flox install' uses last activated environment

set flox $env(FLOX_BIN)

set timeout 10
# activate environment 1
spawn $flox activate --dir 1
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

expect -ex "Preparing environment" {}

# activate environment 2
set cmd "$flox activate --dir 2"
send "$cmd\n"
expect -ex "Preparing environment" {}

# install hello and check it's installed to environment 2
set cmd "$flox install hello"
send "$cmd\n"
expect -re "✅ 'hello' installed to environment '2'" {}
send "hello\n"
expect -ex "Hello, world!" {}

send "exit\n"
send "exit\n"
expect eof
