# Test 'flox install' prompts when an environment is activated and there is an environment in the current directory

set flox $env(FLOX_BIN)
set timeout 20

# activate environment 1
spawn $flox activate --dir 1
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

# wait until we see the environment "greeting" message
expect -ex "To stop using this environment, type 'exit'" {}

# cd to directory 2
send "cd 2\n"
expect "cd 2" {}

# install hello and expect an interactive prompt
send "$flox install hello\n"
expect -ex "Do you want to install to the current directory's flox environment or the current active flox environment?" {}
expect -re {current directory's flox environment \[2 at .*2\]} {}
expect -re {current active flox environment \[1 at .*1\]} {}
expect -re "type to filter.*\n"

# choose the first option and expect the corresponding installation
send "\r"
# install hello and check it's installed to environment 2, but not into environment 1
expect -re "✅ 'hello' installed to environment 2 at .*2" {}
send "command -v hello\n"
send "echo error code: $?\n"
expect -re "error code: 1" {}

send "exit\n"
expect eof
