# Activate a project environment using --dir and check an alias is loaded from
# ~/.bashrc

set dir [lindex $argv 0]
set flox $env(FLOX_BIN)

set timeout 3
spawn $flox activate --dir $dir
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

# The prompt will be "(python) flox [name] (python) ..." if the venv is
# activated twice, so specifically check that the first character after
# "[name]" is not a "(".
expect -re "^\\\(python\\\) flox \\\[name\\\] \[^\(\]" {}
send "$flox list -c\r"
send "type activate || exit 1\r"
send "type deactivate || exit 1\r"
send "exit\r"
expect eof
