use std::collections::BTreeMap;
use std::io::{self, Write};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::{LazyLock, Mutex};
use std::time::{Duration, Instant};

use flox_core::activate::mode::ActivateMode;
use flox_manifest::parsed::common::ContainerizeConfig;
use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;
use thiserror::Error;
use tracing::{Span, debug, info, instrument};
use tracing_indicatif::span_ext::IndicatifSpanExt;

use super::buildenv::BuiltStorePath;
use crate::flox::Flox;
use crate::providers::build::COMMON_NIXPKGS_URL;
use crate::providers::nix::nix_base_command;
use crate::utils::gomap::GoMap;
use crate::utils::{CommandExt, FLOX_INTERPRETER, ReaderExt};

static MK_CONTAINER_NIX: LazyLock<PathBuf> = LazyLock::new(|| {
    std::env::var("FLOX_MK_CONTAINER_NIX")
        .unwrap_or_else(|_| env!("FLOX_MK_CONTAINER_NIX").to_string())
        .into()
});

pub trait ContainerBuilder {
    type Error: std::error::Error;
    fn create_container_source(
        &self,
        flox: &Flox,
        name: impl AsRef<str>,
        tag: impl AsRef<str>,
    ) -> Result<ContainerSource, Self::Error>;
}

/// OCI representation of our more user-friendly `ManifestContainerizeConfig`.
#[skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "PascalCase")]
pub struct OCIConfig {
    user: Option<String>,
    exposed_ports: Option<GoMap>,
    cmd: Option<Vec<String>>,
    volumes: Option<GoMap>,
    working_dir: Option<String>,
    labels: Option<BTreeMap<String, String>>,
    stop_signal: Option<String>,
}

impl From<ContainerizeConfig> for OCIConfig {
    fn from(config: ContainerizeConfig) -> Self {
        Self {
            user: config.user,
            exposed_ports: config.exposed_ports.map(GoMap::from),
            cmd: config.cmd,
            volumes: config.volumes.map(GoMap::from),
            working_dir: config.working_dir,
            labels: config.labels,
            stop_signal: config.stop_signal,
        }
    }
}

/// An implementation of [ContainerBuilder] that uses a Nix script
/// to build a native [ContainerSource] from a [BuiltStorePath].
///
/// [MK_CONTAINER_NIX] is a Nix script that uses nixpkgs' `dockerTools.streamLayeredImage`
/// which produces a script which that composes store paths
/// as layers of a container image, and writes the resulting image to `stdout`.
/// [MkContainerNix::create_container_source] performs the build of that script,
/// which in turn builds all the required layers.
/// The resulting [ContainerSource] will execute the script
/// and stream the container image to a given sink via [ContainerSource::stream_container].
///
/// Note: that this implementation is not suitable for building containers on macOS.
///
/// 1. Containers are native _linux_ systems, for which packages can't be built on macOS.
/// 2. The script generated by `dockerTools.streamLayeredImage` is not compatible with macOS.
#[derive(Debug)]
pub struct MkContainerNix {
    store_path: BuiltStorePath,
    activation_mode: ActivateMode,
    container_config: Option<OCIConfig>,
    /// Path to the flox binary to include in the container image.
    ///
    /// When set, mkContainer.nix adds the binary to the image and populates
    /// `flox_bin` in the baked activation context so the guest shell finds
    /// a real `flox` instead of the deactivate-only shim.
    flox_bin: PathBuf,
    /// When true, pass `openshellCompat = true` to mkContainer.nix.
    ///
    /// This adds the `sandbox` user/group, `iproute2`, and `/bin/sh` to the
    /// guest image — all required by the OpenShell supervisor. The flag is
    /// set only by the `openshell` sandbox backend bake; all other callers
    /// leave it false so the `oci` backend and plain `flox containerize` are
    /// byte-identical to today.
    openshell_compat: bool,
}

#[derive(Debug, Error)]
pub enum MkContainerNixError {
    #[error("failed to call nix")]
    CallNixError(#[source] std::io::Error),

    #[error("failed to build container: {0}")]
    BuildContainerError(String),

    #[error("failed to parse nix build output")]
    ParseBuildOutput(#[source] serde_json::Error),

    #[error("couldn't serialize container config")]
    SerializeContainerConfig(#[source] serde_json::Error),
}

impl MkContainerNix {
    /// Create a new [MkContainerNix] instance that will build a container
    /// from the given [BuiltStorePath].
    /// Generally, this should be the output of a [crate::providers::buildenv::BuildEnv::build].
    ///
    /// Note: this constructor is only available on Linux.
    /// On macOS, use a macOS-specific implementation of [ContainerBuilder].
    #[cfg_attr(
        not(target_os = "linux"),
        deprecated(note = "MkContainerNix is not supported on this platform")
    )]
    pub fn new(
        store_path: BuiltStorePath,
        activation_mode: ActivateMode,
        container_config: Option<OCIConfig>,
        flox_bin: PathBuf,
    ) -> Self {
        Self {
            store_path,
            activation_mode,
            container_config,
            flox_bin,
            openshell_compat: false,
        }
    }

    /// Variant of [`new`] that also enables the OpenShell compat layer in
    /// `mkContainer.nix`. Used only by the `openshell` sandbox backend bake.
    pub fn new_with_openshell_compat(
        store_path: BuiltStorePath,
        activation_mode: ActivateMode,
        container_config: Option<OCIConfig>,
        flox_bin: PathBuf,
    ) -> Self {
        Self {
            store_path,
            activation_mode,
            container_config,
            flox_bin,
            openshell_compat: true,
        }
    }

    /// Build the `--argstr NAME VALUE` argument list passed to
    /// `nix build --file mkContainer.nix`.
    ///
    /// The `floxBin` argstr is emitted only when `flox_bin` is non-empty,
    /// so a guest without a real flox binary omits it and mkContainer.nix
    /// falls back to the deactivate-only shim.
    fn argstr_args(&self, name: &str, tag: &str) -> Result<Vec<String>, MkContainerNixError> {
        let mut args = vec![
            "--argstr".into(),
            "nixpkgsFlakeRef".into(),
            COMMON_NIXPKGS_URL.to_string(),
            "--argstr".into(),
            "containerSystem".into(),
            env!("NIX_TARGET_SYSTEM").into(),
            "--argstr".into(),
            "system".into(),
            env!("NIX_TARGET_SYSTEM").into(),
            "--argstr".into(),
            "environmentOutPath".into(),
            self.store_path.to_string_lossy().into_owned(),
            "--argstr".into(),
            "activationMode".into(),
            self.activation_mode.to_string(),
            "--argstr".into(),
            "interpreterPath".into(),
            (*FLOX_INTERPRETER).to_string_lossy().into_owned(),
        ];
        if !self.flox_bin.as_os_str().is_empty() {
            args.extend([
                "--argstr".into(),
                "floxBin".into(),
                self.flox_bin.to_string_lossy().into_owned(),
            ]);
        }
        if self.openshell_compat {
            // Nix booleans require `--arg` (not `--argstr`) so the value is
            // parsed as a Nix expression rather than a string literal.
            args.extend(["--arg".into(), "openshellCompat".into(), "true".into()]);
        }
        args.extend([
            "--argstr".into(),
            "containerName".into(),
            name.to_string(),
            "--argstr".into(),
            "containerTag".into(),
            tag.to_string(),
        ]);
        if let Some(container_config) = &self.container_config {
            args.extend([
                "--argstr".into(),
                "containerConfigJSON".into(),
                serde_json::to_string(container_config)
                    .map_err(MkContainerNixError::SerializeContainerConfig)?,
            ]);
        }
        Ok(args)
    }
}

impl ContainerBuilder for MkContainerNix {
    type Error = MkContainerNixError;

    /// Create a [ContainerSource] that will assemble a container image.
    /// The container image will be built from the provided [BuiltStorePath],
    /// which is generally the output of a [crate::providers::buildenv::BuildEnv::build].
    /// The streaming script will be built via `nix build`.
    #[instrument(skip_all, fields(
        name = name.as_ref(),
        tag = tag.as_ref(),
        progress = "Building container layers"))]
    fn create_container_source(
        &self,
        _flox: &Flox,
        name: impl AsRef<str>,
        tag: impl AsRef<str>,
    ) -> Result<ContainerSource, Self::Error> {
        let mut command = nix_base_command();
        command.arg("build");
        command.arg("--json");
        command.arg("--no-link");
        command.arg("--file").arg(&*MK_CONTAINER_NIX);
        command.args(self.argstr_args(name.as_ref(), tag.as_ref())?);
        debug!(cmd=%command.display(), "building container");

        let output = command
            .output()
            .map_err(MkContainerNixError::CallNixError)?;
        if !output.status.success() {
            return Err(MkContainerNixError::BuildContainerError(
                String::from_utf8_lossy(&output.stderr).to_string(),
            ));
        }

        // defined inline as an implementation detail
        #[derive(Debug, Clone, Deserialize)]
        struct MkContainerOutputs {
            out: PathBuf,
        }

        #[derive(Debug, Clone, Deserialize)]
        struct MkContainerResultRaw {
            outputs: MkContainerOutputs,
        }

        let [raw @ MkContainerResultRaw { .. }] = serde_json::from_slice(&output.stdout)
            .map_err(MkContainerNixError::ParseBuildOutput)?;
        let container_builder_script_path = raw.outputs.out;
        let container_source = ContainerSource::new(Command::new(container_builder_script_path));

        Ok(container_source)
    }
}

/// Minimum interval between spinner label updates driven by builder stderr.
/// Nix build output can be very chatty; throttling prevents flicker.
const SPINNER_UPDATE_INTERVAL: Duration = Duration::from_millis(500);

/// Maximum length of a spinner label snippet taken from a builder line.
const SPINNER_SNIPPET_MAX_CHARS: usize = 60;

/// Rate-limits spinner label updates derived from subprocess output lines.
///
/// Blank lines never produce an update. Non-blank lines produce a truncated
/// snippet at most once per interval; suppressed lines do not reset the
/// interval timer.
#[derive(Debug)]
struct SpinnerThrottle {
    interval: Duration,
    last_update: Option<Instant>,
}

impl SpinnerThrottle {
    fn new(interval: Duration) -> Self {
        Self {
            interval,
            last_update: None,
        }
    }

    /// Returns a spinner-ready snippet (trimmed, truncated to
    /// [`SPINNER_SNIPPET_MAX_CHARS`]) when `line` should update the label,
    /// or `None` when the line is blank or arrives before the interval has
    /// elapsed since the last accepted line.
    fn accept(&mut self, line: &str, now: Instant) -> Option<String> {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            return None;
        }
        if let Some(last) = self.last_update
            && now.duration_since(last) < self.interval
        {
            return None;
        }
        self.last_update = Some(now);
        Some(trimmed.chars().take(SPINNER_SNIPPET_MAX_CHARS).collect())
    }
}

/// Type representing a container source,
/// i.e. a command that writes a container tarball to stdout.
/// This is typically created by [ContainerBuilder::create_container_source].
#[derive(Debug)]
pub struct ContainerSource {
    source_command: Command,
}

impl ContainerSource {
    pub fn new(source_command: Command) -> Self {
        Self { source_command }
    }

    /// Run the container builder script
    /// and write the container tarball to the given sink.
    ///
    /// Stderr from the builder process is forwarded via `info!` for verbose
    /// output (`-v`). Concurrently, the latest interesting builder line is
    /// surfaced (throttled) as the progress bar message of this function's
    /// span via [`IndicatifSpanExt::pb_set_message`], so the user sees motion
    /// during the long compile stage without needing `-v`. The logger's
    /// progress template renders the message after the static stage label
    /// carried by the `progress` field.
    #[instrument(skip_all, fields(command = ?self.source_command, progress = "[2/3] Writing container layers"))]
    pub fn stream_container(self, sink: &mut impl Write) -> Result<(), ContainerSourceError> {
        let mut container_source_command = self.source_command;

        // ensure the command writes to stdout
        container_source_command.stdout(Stdio::piped());
        container_source_command.stderr(Stdio::piped());

        debug!(
            "running container source command: {}",
            container_source_command.display()
        );

        let mut handle = container_source_command
            .spawn()
            .map_err(ContainerSourceError::CallContainerSourceCommand)?;

        // The span handle carries its own subscriber reference, so
        // pb_set_message works from the tap thread below (and gracefully
        // no-ops when no indicatif layer is registered, e.g. in tests).
        let span = Span::current();
        let throttle = Mutex::new(SpinnerThrottle::new(SPINNER_UPDATE_INTERVAL));

        let tap = handle
            .stderr
            .take()
            .expect("stderr set to piped")
            .tap_lines(move |line| {
                // Forward to info! so -v users still see the raw output.
                info!("{line}");

                let accepted = throttle
                    .lock()
                    .expect("spinner throttle mutex poisoned")
                    .accept(line, Instant::now());
                if let Some(snippet) = accepted {
                    span.pb_set_message(&snippet);
                }
            });

        let mut stdout = handle.stdout.take().expect("stdout set to piped");

        io::copy(&mut stdout, sink).map_err(ContainerSourceError::StreamContainer)?;

        let status = handle
            .wait()
            .map_err(ContainerSourceError::CallContainerSourceCommand)?;

        if !status.success() {
            let stderr_content = tap.wait();
            return Err(ContainerSourceError::CommandUnsuccessful(stderr_content));
        }
        Ok(())
    }
}

#[derive(Debug, Error)]
pub enum ContainerSourceError {
    #[error("failed to call container source command")]
    CallContainerSourceCommand(#[source] std::io::Error),
    #[error("failed to stream container to sink")]
    StreamContainer(#[source] std::io::Error),
    #[error(
        "container source command unsuccessful\n\
        \n\
        stderr:\n\
        {0}"
    )]
    CommandUnsuccessful(String),
}

#[cfg(test)]
mod mk_container_nix_tests {
    use super::*;
    use crate::providers::buildenv::BuiltStorePath;

    fn dummy_store_path() -> BuiltStorePath {
        BuiltStorePath::new_for_test(PathBuf::from("/nix/store/fake-env"))
    }

    /// Return the value that follows the first `--argstr <name>` pair, or
    /// `None` if the argstr is absent.
    fn argstr_value<'a>(args: &'a [String], name: &str) -> Option<&'a str> {
        args.windows(3)
            .find_map(|w| (w[0] == "--argstr" && w[1] == name).then(|| w[2].as_str()))
    }

    /// When a store-path flox binary is provided, the builder must emit
    /// `--argstr floxBin <path>` so mkContainer.nix bakes the real binary.
    #[test]
    fn emits_flox_bin_argstr_when_provided() {
        let bin = PathBuf::from("/nix/store/fake-flox/bin/flox");
        #[allow(deprecated)]
        let builder = MkContainerNix::new(
            dummy_store_path(),
            ActivateMode::default(),
            None,
            bin.clone(),
        );
        let args = builder.argstr_args("env", "latest").unwrap();
        assert_eq!(
            argstr_value(&args, "floxBin"),
            Some(bin.to_string_lossy().as_ref()),
            "floxBin argstr must carry the provided path:\n{args:?}"
        );
    }

    /// When `flox_bin` is empty, the builder must NOT emit a `floxBin`
    /// argstr so mkContainer.nix falls back to the deactivate-only shim.
    #[test]
    fn omits_flox_bin_argstr_when_empty() {
        #[allow(deprecated)]
        let builder = MkContainerNix::new(
            dummy_store_path(),
            ActivateMode::default(),
            None,
            PathBuf::new(),
        );
        let args = builder.argstr_args("env", "latest").unwrap();
        assert_eq!(
            argstr_value(&args, "floxBin"),
            None,
            "floxBin argstr must be absent when flox_bin is empty:\n{args:?}"
        );
    }
}

#[cfg(test)]
mod spinner_throttle_tests {
    use std::io::Cursor;
    use std::sync::Arc;

    use super::*;

    #[test]
    fn accepts_after_interval_elapses() {
        let mut throttle = SpinnerThrottle::new(Duration::from_millis(100));
        let t0 = Instant::now();
        assert_eq!(throttle.accept("first", t0), Some("first".to_string()));
        assert_eq!(
            throttle.accept("too soon", t0 + Duration::from_millis(50)),
            None
        );
        assert_eq!(
            throttle.accept("later", t0 + Duration::from_millis(150)),
            Some("later".to_string())
        );
    }

    #[test]
    fn skips_blank_lines_without_consuming_interval() {
        let mut throttle = SpinnerThrottle::new(Duration::from_millis(100));
        let t0 = Instant::now();
        assert_eq!(throttle.accept("   ", t0), None);
        assert_eq!(throttle.accept("", t0), None);
        // Blank lines do not start the interval; the first real line is
        // accepted immediately.
        assert_eq!(throttle.accept("real", t0), Some("real".to_string()));
    }

    #[test]
    fn truncates_long_lines_to_snippet_length() {
        let mut throttle = SpinnerThrottle::new(Duration::ZERO);
        let long = "x".repeat(SPINNER_SNIPPET_MAX_CHARS + 20);
        let snippet = throttle.accept(&long, Instant::now()).unwrap();
        assert_eq!(snippet.chars().count(), SPINNER_SNIPPET_MAX_CHARS);
    }

    #[test]
    fn gates_tap_lines_updates_to_one_per_interval() {
        // All lines from an in-memory reader arrive well within one
        // interval, so only the first non-blank line may produce an update.
        let input = "unpacking sources\n\nbuilding\ninstalling\n";
        let throttle = Mutex::new(SpinnerThrottle::new(Duration::from_secs(60)));
        let updates = Arc::new(Mutex::new(Vec::new()));
        let updates_in_tap = Arc::clone(&updates);
        let tap = Cursor::new(input.as_bytes().to_vec()).tap_lines(move |line| {
            let accepted = throttle.lock().unwrap().accept(line, Instant::now());
            if let Some(snippet) = accepted {
                updates_in_tap.lock().unwrap().push(snippet);
            }
        });
        tap.wait();
        assert_eq!(*updates.lock().unwrap(), vec![
            "unpacking sources".to_string()
        ]);
    }
}

#[cfg(test)]
mod container_source_tests {
    use std::collections::BTreeSet;
    use std::fs::{self, File};
    use std::os::unix::fs::PermissionsExt;

    use indoc::indoc;
    use tempfile::TempDir;

    use super::*;

    #[test]
    fn oci_config_from_manifest() {
        let manifest_config = ContainerizeConfig {
            user: Some("root".to_string()),
            exposed_ports: Some(BTreeSet::from(["80/tcp".to_string()])),
            volumes: Some(BTreeSet::from(["/app".to_string()])),
            working_dir: Some("/app".to_string()),
            labels: Some(BTreeMap::from([
                ("app".to_string(), "myapp".to_string()),
                ("version".to_string(), "1.0".to_string()),
            ])),
            ..Default::default()
        };
        let oci_config: OCIConfig = manifest_config.into();
        let json = serde_json::to_string_pretty(&oci_config).unwrap();

        // Selection of fields that verify From + Serialize:
        // - omits fields that are `None`
        // - renames keys from kebab-case to PascalCase
        // - converts values from `BTreeSet` to `GoMap`
        assert_eq!(json, indoc! {r#"{
          "User": "root",
          "ExposedPorts": {
            "80/tcp": {}
          },
          "Volumes": {
            "/app": {}
          },
          "WorkingDir": "/app",
          "Labels": {
            "app": "myapp",
            "version": "1.0"
          }
        }"#});
    }

    /// OS error 26 is "Text file busy",
    /// which can happen when executing a script
    /// that is has been written to immediately before.
    /// We typically see this in tests, where we write
    /// a new script and immediately execute it.
    /// In production use, this should not happen as the script
    /// will be written by a different process (`nix`).
    ///
    /// <https://github.com/rust-lang/rust/issues/114554>
    const ERR_TEXT_FILE_BUSY: i32 = 26;

    const TEST_BUILDER: &str = indoc! {r#"
        #!/usr/bin/env bash
        echo "hello world"
    "#};

    fn create_test_script() -> (TempDir, PathBuf) {
        let tempdir = tempfile::tempdir().unwrap();
        let path = tempdir.path().join("flox-test-container-builder");
        std::fs::write(&path, TEST_BUILDER).unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).unwrap();
        (tempdir, path)
    }

    #[test]
    fn test_writes_output_to_writer() {
        let (_tempdir, test_script) = create_test_script();

        let mut buf = Vec::new();

        let mut tries = 0;
        loop {
            if tries >= 3 {
                panic!("Test flaked with 'Text file busy' and can be re-run")
            }
            let container_builder = ContainerSource::new(Command::new(&test_script));
            match container_builder.stream_container(&mut buf) {
                Err(ContainerSourceError::CallContainerSourceCommand(e))
                    if e.raw_os_error() == Some(ERR_TEXT_FILE_BUSY) =>
                {
                    dbg!("Text file busy -- ignored");
                    tries += 1;
                    continue;
                },
                result => break result.unwrap(),
            }
        }
        assert_eq!(buf, b"hello world\n");
    }

    #[test]
    fn test_allows_forwarding_to_file() {
        let (tempdir, test_script) = create_test_script();
        let output_path = tempdir.path().join("output");

        let mut file = File::create(&output_path).unwrap();

        // looping to ignore "Text file busy" errors
        // see the comment on `ERR_TEXT_FILE_BUSY` for more information
        let mut tries = 0;
        loop {
            if tries >= 3 {
                panic!("Test flaked with 'Text file busy' and can be re-run")
            }
            let container_builder = ContainerSource::new(Command::new(&test_script));
            match container_builder.stream_container(&mut file) {
                Err(ContainerSourceError::CallContainerSourceCommand(e))
                    if e.raw_os_error() == Some(ERR_TEXT_FILE_BUSY) =>
                {
                    dbg!("Text file busy -- ignored");
                    tries += 1;
                    continue;
                },
                result => break result.unwrap(),
            }
        }
        drop(file);

        let output = fs::read_to_string(&output_path).unwrap();
        assert_eq!(output, "hello world\n");
    }
}
