set env_ref [lindex $argv 0]
set question [lindex $argv 1]
set answer [lindex $argv 2]
set flox $env(FLOX_BIN)

# activate environment 1
set timeout 40
spawn $flox pull --remote $env_ref
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

expect -ex "$question" {}

if { $answer == "yes" } {
  # Down arrow
  send "\033\[B"
}

send "\r"

expect eof
