set env_ref [lindex $argv 0]
set system [lindex $argv 1]
set answer [lindex $argv 2]
set flox $env(FLOX_BIN)

# activate environment 1
set timeout 20
spawn $flox pull --remote $env_ref
expect_after {
  timeout { exit 1 }
  eof { exit 2 }
  "*\n" { exp_continue }
  "*\r" { exp_continue }
}

expect -ex "The environment you are trying to pull is not compatible with your system ($system)." {}
expect -ex "Would you like to add your system to the list of compatible systems in the manifest?" {}

send "$answer\r"

expect eof
