use std::collections::HashMap;
use std::path::Path;

use anyhow::{Context, Result};

use crate::attach_diff::FLOX_ENV_DIRS_VAR;
use crate::env_diff::EnvDiff;

/// Skip `BASH_FUNC_*` variables which are generated by `export -f` or `unset -f`
/// in hooks and result in keys containing `%%` that are invalid in other userShells.
const BASH_EXPORTED_FUNC_PREFIX: &str = "BASH_FUNC_";

pub const ENV_DIFF_START_JSON: &str = "start.env.json";
pub const ENV_DIFF_END_JSON: &str = "end.env.json";

/// Environment variables captured while running the activate script
#[derive(Debug, Default, Clone)]
pub struct StartDiff {
    diff: EnvDiff,
    /// Start-snapshot values of the variables that appear in `additions`,
    /// plus `FLOX_ENV_DIRS`. These record the context the start ran in so
    /// that PATH-like additions can be replayed relative to the attaching
    /// context instead of verbatim.
    start_values: HashMap<String, String>,
}

impl StartDiff {
    /// Variable additions observed after the start hook ran.
    pub fn additions(&self) -> &HashMap<String, String> {
        &self.diff.additions
    }

    /// Variable deletions observed after the start hook ran.
    pub fn deletions(&self) -> &[String] {
        &self.diff.deletions
    }

    /// The value the variable had at the start snapshot, i.e. before the
    /// profile.d scripts and `hook.on-activate` ran.
    pub fn start_value(&self, name: &str) -> Option<&str> {
        self.start_values.get(name).map(String::as_str)
    }

    /// The `FLOX_ENV_DIRS` the start ran with: the environment stack that
    /// was active when this environment first activated.
    pub fn start_env_dirs(&self) -> Option<&str> {
        self.start_value(FLOX_ENV_DIRS_VAR)
    }

    /// Load a StartDiff from start.env.json and end.env.json files in activation_state_dir
    pub fn from_files(activation_state_dir: impl AsRef<Path>) -> Result<StartDiff> {
        let start_json = activation_state_dir.as_ref().join(ENV_DIFF_START_JSON);
        let end_json = activation_state_dir.as_ref().join(ENV_DIFF_END_JSON);

        let start_env = parse_env_json(&start_json)
            .with_context(|| format!("Failed to read {}", start_json.display()))?;
        let end_env = parse_env_json(&end_json)
            .with_context(|| format!("Failed to read {}", end_json.display()))?;

        Ok(from_parsed_files(&start_env, &end_env))
    }

    #[cfg(test)]
    pub fn from_parts(additions: HashMap<String, String>, deletions: Vec<String>) -> Self {
        StartDiff {
            diff: EnvDiff::from_parts(additions, deletions),
            start_values: HashMap::new(),
        }
    }

    #[cfg(test)]
    pub fn from_parts_with_start_values(
        additions: HashMap<String, String>,
        deletions: Vec<String>,
        start_values: HashMap<String, String>,
    ) -> Self {
        StartDiff {
            diff: EnvDiff::from_parts(additions, deletions),
            start_values,
        }
    }
}

/// Parse a JSON environment file (output of `jq -nS env`) into a HashMap.
///
/// The JSON file should be an object with environment variable names as keys
/// and their values as string values.
fn parse_env_json(path: impl AsRef<Path>) -> Result<HashMap<String, String>> {
    let contents = std::fs::read_to_string(path.as_ref())?;
    Ok(serde_json::from_str(&contents)?)
}

fn from_parsed_files(
    start_env: &HashMap<String, String>,
    end_env: &HashMap<String, String>,
) -> StartDiff {
    let mut additions = HashMap::new();
    let mut deletions = Vec::new();
    let mut start_values = HashMap::new();

    for key in start_env.keys() {
        if key.starts_with(BASH_EXPORTED_FUNC_PREFIX) {
            continue;
        }
        if !end_env.contains_key(key) {
            deletions.push(key.clone());
        }
    }
    for (key, value) in end_env {
        if key.starts_with(BASH_EXPORTED_FUNC_PREFIX) {
            continue;
        }
        if start_env.get(key) != Some(value) {
            additions.insert(key.clone(), value.clone());
            if let Some(start_value) = start_env.get(key) {
                start_values.insert(key.clone(), start_value.clone());
            }
        }
    }
    if let Some(env_dirs) = start_env.get(FLOX_ENV_DIRS_VAR) {
        start_values.insert(FLOX_ENV_DIRS_VAR.to_string(), env_dirs.clone());
    }
    StartDiff {
        diff: EnvDiff::from_parts(additions, deletions),
        start_values,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_parsed_files_records_start_values() {
        let start_env = HashMap::from([
            ("CPATH".to_string(), "/envs/core/include".to_string()),
            (FLOX_ENV_DIRS_VAR.to_string(), "/envs/core".to_string()),
            ("UNCHANGED".to_string(), "same".to_string()),
        ]);
        let end_env = HashMap::from([
            (
                "CPATH".to_string(),
                "/envs/pi/include:/envs/core/include".to_string(),
            ),
            ("CREATED".to_string(), "new".to_string()),
            (FLOX_ENV_DIRS_VAR.to_string(), "/envs/core".to_string()),
            ("UNCHANGED".to_string(), "same".to_string()),
        ]);

        let diff = from_parsed_files(&start_env, &end_env);

        // The start value is recorded for changed vars, absent for created
        // vars, and FLOX_ENV_DIRS is always recorded even when unchanged.
        assert_eq!(
            diff.start_values,
            HashMap::from([
                ("CPATH".to_string(), "/envs/core/include".to_string()),
                (FLOX_ENV_DIRS_VAR.to_string(), "/envs/core".to_string()),
            ])
        );
        assert_eq!(diff.start_value("CPATH"), Some("/envs/core/include"));
        assert_eq!(diff.start_value("CREATED"), None);
        assert_eq!(diff.start_env_dirs(), Some("/envs/core"));
    }

    #[test]
    fn test_from_parsed_files_insertion() {
        let start_env = HashMap::from([("VAR1".to_string(), "value1".to_string())]);
        let end_env = HashMap::from([
            ("VAR1".to_string(), "value1".to_string()),
            ("VAR2".to_string(), "value2".to_string()),
        ]);

        let diff = from_parsed_files(&start_env, &end_env);

        assert_eq!(
            diff.additions(),
            &HashMap::from([("VAR2".to_string(), "value2".to_string()),])
        );
        assert!(diff.deletions().is_empty());
    }

    #[test]
    fn test_from_parsed_files_deletion() {
        let start_env = HashMap::from([("VAR1".to_string(), "value1".to_string())]);
        let end_env = HashMap::new();

        let diff = from_parsed_files(&start_env, &end_env);

        assert!(diff.additions().is_empty());
        assert_eq!(diff.deletions(), ["VAR1".to_string()]);
    }

    #[test]
    fn test_from_parsed_files_unchanged() {
        let start_env = HashMap::from([("VAR1".to_string(), "value1".to_string())]);

        let diff = from_parsed_files(&start_env, &start_env);

        assert!(diff.additions().is_empty());
        assert!(diff.deletions().is_empty());
    }

    #[test]
    fn test_from_parsed_files_changed_value() {
        let start_env = HashMap::from([("VAR1".to_string(), "old_value".to_string())]);
        let end_env = HashMap::from([("VAR1".to_string(), "new_value".to_string())]);

        let diff = from_parsed_files(&start_env, &end_env);

        assert_eq!(
            diff.additions(),
            &HashMap::from([("VAR1".to_string(), "new_value".to_string())])
        );
        assert!(diff.deletions().is_empty());
    }

    #[test]
    fn test_from_parsed_files_filters_bash_func_additions() {
        let start_env = HashMap::new();
        let end_env = HashMap::from([
            ("VAR1".to_string(), "value1".to_string()),
            ("BASH_FUNC__foo%%".to_string(), "() { true; }".to_string()),
            ("BASH_FUNC_bar%%".to_string(), "() { false; }".to_string()),
        ]);

        let diff = from_parsed_files(&start_env, &end_env);

        assert_eq!(
            diff.additions(),
            &HashMap::from([("VAR1".to_string(), "value1".to_string())])
        );
        assert_eq!(diff.deletions(), Vec::<String>::new());
    }

    #[test]
    fn test_from_parsed_files_filters_bash_func_deletions() {
        let start_env = HashMap::from([
            ("VAR1".to_string(), "value1".to_string()),
            ("BASH_FUNC__foo%%".to_string(), "() { true; }".to_string()),
            ("BASH_FUNC_bar%%".to_string(), "() { false; }".to_string()),
        ]);
        let end_env = HashMap::new();

        let diff = from_parsed_files(&start_env, &end_env);

        assert_eq!(diff.additions(), &HashMap::new());
        assert_eq!(diff.deletions(), vec!["VAR1".to_string()]);
    }
}
