set attr [lindex $argv 0]
set flox $env(FLOX_CLI)
if {$attr eq ""} {
    spawn $flox -v develop
} else {
    spawn $flox -v develop $attr
}
set timeout 30
expect {
    -re "(fetching|downloading)" {
        # fetching needs a higher timeout
        set timeout 90
        expect {
            "activating floxEnv" {}
            timeout { exit 1 }
        }
        set timeout 30
    }
    "activating floxEnv" {}
    timeout { exit 1 }
}
expect {
    "developing package" {}
    timeout { exit 1 }
}
expect {
    -re "\$" {
        send "{ command -v rg||which rg||type -P rg; } 2>&1\n"
        expect {
            -re "/nix/store/.*-ripgrep-13.0.0/bin/rg" {}
            timeout { exit 1 }
        }
    }
    timeout { exit 1 }
}
expect {
    -re "\$" {
        send "{ command -v curl||which curl||type -P curl; } 2>&1\n"
        expect {
            -re ".*/(develop|toplevel-flox-nix-with-pkg)/.flox/envs/.*(my-pkg|default)/bin/curl" {}
            timeout { exit 1 }
        }
    }
    timeout { exit 1 }
}
expect {
    -re "\$" {
        send "exit\r"
        expect eof
    }
    timeout { exit 0 }
}
exit 0
