set attr [lindex $argv 0]
set flox $env(FLOX_CLI)
if {$attr eq ""} {
    set cmd "$flox --bash-passthru -v develop"
    spawn $flox --bash-passthru -v develop
} else {
    set cmd "$flox --bash-passthru -v develop $attr"
    spawn $flox --bash-passthru -v develop $attr
}
set timeout 60
expect {
    -re "(fetching|downloading)" {
        # fetching needs a higher timeout
        set timeout 90
        expect {
            "activating floxEnv" {}
            timeout {
              puts stderr "Reached timeout running '$cmd'"
              exit 1
            }
        }
        set timeout 30
    }
    "activating floxEnv" {}
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}
expect {
    -re "\$" {
        send "{ command -v hello||which hello||type -P hello; } 2>&1\n"
        expect {
            -re ".*/toplevel-flox-nix/.flox/envs/.*default/bin/hello" {}
            timeout {
              puts stderr "Reached timeout locating 'hello'"
              exit 1
            }
        }
    }
    timeout {
      puts stderr "Reached timeout running '$cmd'"
      exit 1
    }
}
expect {
    -re "\$" {
        send "exit\r"
        expect eof
    }
    timeout {
      puts stderr "Reached timeout locating 'hello'"
      exit 0
    }
}
exit 0
