set attr [lindex $argv 0]
set flox $env(FLOX_CLI)
if {$attr eq ""} {
    spawn $flox -v develop
} else {
    spawn $flox -v develop $attr
}
set timeout 30
expect {
    -re "(fetching|downloading)" {
        # fetching needs a higher timeout
        set timeout 90
        expect {
            "activating floxEnv" {}
            timeout { exit 1 }
        }
        set timeout 30
    }
    "activating floxEnv" {}
    timeout { exit 1 }
}
expect {
    -re "\$" {}
    timeout { exit 1 }
}
send "which hello\n"
expect {
    -re ".*/toplevel-flox-nix/.flox/envs/.*default/bin/hello" {}
    timeout { exit 1 }
}
send "exit\r"
expect eof
