version = 1

[install]
hello.pkg-path = "hello"

[build]

myhello.command = '''
  mkdir -p $out/bin
  echo echo hello foo > $out/bin/hello
  echo exec hello >> $out/bin/hello
  chmod +x $out/bin/hello
'''
myhello.runtime-packages = [ "hello", "goodbye" ]
