---
config:
  theme: mc
  layout: dagre
---
flowchart TB
 subgraph cli["flox-activations with activate"]
        s3["Registry Module"]
        match_activation_mode{"activation mode?"}
        n37[["exec(userShell<br>&lt;RCFILE_options&gt;)"]]
        n35[["activate_in_place()"]]
        n83["print(flox-activations attach --pid X --remove Y)<br>replay environment, run profile scripts, set activation variables, etc."]
        n137["start services?"]
        n145["exec(userShell<br>&lt;RCFILE_options&gt;<br>-c command_script)"]
        apply_activation_env_exec["apply_activation_env()"]
        apply_activation_env_shell["apply_activation_env()"]
        apply_activation_env_interactive["apply_activation_env()"]
        invoke["userShell"]
        n155["wait_for_process_compose()"]
        pc_start@{ label: "<span style=\"background-color:\">subprocess(process-compose start)</span>" }
        n157["subprocess(process-compose list)<br>to verify running"]
        exec_cmd["exec(cmd args)"]
  end
 subgraph s2["process-compose"]
        n98["flox-never-exit"]
  end
 subgraph s3["<br>"]
        n114["TODO state logic"]
  end
 subgraph activate["start.bash"]
        n7[["Capture start.env.json"]]
        n6["source etc-profiles"]
        nd["set_manifest_vars<br>source hook.on-activate<br>"]
        n63[["Capture end.env.json"]]
  end
 subgraph colorkey["Color Key"]
        node_aqepkktvr["rust"]
        n0["bash"]
        nz["userShell"]
        n110["state.json<br>logic<br>(in rust)"]
  end
 subgraph executive["Executive"]
        ns[["Monitoring loop"]]
        ny[["Clean up activation state directory"]]
        n66[["stop-process-compose()"]]
        n125["register SIGUSR1 signal handler<br>"]
        n100@{ label: "- setsid()<br style=\"--tw-scale-x:\">- register as subreaper (Linux)<br><span style=\"padding-left:\">- register SIGUSR1 signal handler</span>" }
        n148["SIGUSR1 signal handler:<br>start_process_compose()<br>using latest store path in activation state"]
        s2
        n162["PIDs exited?"]
        n163["Cleanup stale start state directories"]
  end
 subgraph invoke["userShell"]
    direction TB
        n82(["interactive or command"])
        n141@{ label: "<span style=\"background-color:\">Profile scripts</span><br>" }
        n142["Replay environment, set activation variables, etc."]
        n143["source user dotfiles"]
  end
 subgraph s4["Flox CLI w tokio"]
        n88["parse args"]
        n89{"activate()<br>services(start)"}
        n36["Initialise ActivateCtx"]
  end
    ns --> n162
    node_aqepkktvr ~~~ n0
    n0 ~~~ nz
    n137 -- continue if activating --> match_activation_mode
    match_activation_mode -- in place --> n35
    match_activation_mode -- "flox activate -- cmd args" --> apply_activation_env_exec
    match_activation_mode -- interactive --> apply_activation_env_interactive
    apply_activation_env_exec --> exec_cmd
    nd --> n63
    A(["Parent PID<br>flox activate<br>"]) -- fork() &amp;&amp; exec(flox) --> n88
    n88 --> n89
    n89 --> n36
    n100 ~~~ n7
    nz ~~~ n110
    n125 --> n100
    n35 --> n83
    n66 --> ny
    n141 --> n82
    n142 --> n141
    n37 --> invoke
    n145 --> invoke
    n155 --> pc_start
    n155 -- SIGUSR1 --> n148
    n137 -- yes --> n155
    pc_start --> n157
    n148 --> s2
    n100 --> ns
    n100 -- SIGUSR1 --> s3
    n162 -- All PIDs --> n66
    n162 -- Some PIDs --> n163
    n163 --> ns
    n162 -- No PIDs --> ns
    n143 --> n142
    s3 -- child --> n125
    s3 -- subprocess --> n7
    s3 --> n137
    n160(["Container entrypoint"]) --> s3
    n36 --> s3
    match_activation_mode -- "<span style=padding-left:>flox activate -c 'command script'</span>" --> apply_activation_env_shell
    apply_activation_env_shell --> n145
    apply_activation_env_interactive --> n37
    n7 --> n6
    n6 --> nd

    n83@{ shape: doc}
    n137@{ shape: diam}
    pc_start@{ shape: rect}
    n114@{ shape: rect}
    n100@{ shape: rect}
    n162@{ shape: diam}
    n141@{ shape: subproc}
    n142@{ shape: rect}
    style s3 fill:transparent
    style match_activation_mode fill:#FFE0B2
    style n37 fill:#FFE0B2
    style n35 fill:#FFE0B2
    style n83 fill:#FFE0B2
    style n137 fill:#FFE0B2
    style n145 fill:#FFE0B2
    style apply_activation_env_exec fill:#FFE0B2
    style apply_activation_env_shell fill:#FFE0B2
    style apply_activation_env_interactive fill:#FFE0B2
    style n155 fill:#FFE0B2
    style pc_start fill:#FFE0B2
    style n157 fill:#FFE0B2
    style exec_cmd fill:#FFE0B2
    style n114 fill:#C8E6C9
    style n7 fill:#BBDEFB
    style n6 fill:#BBDEFB
    style nd fill:#BBDEFB
    style n63 fill:#BBDEFB
    style node_aqepkktvr fill:#FFE0B2
    style n0 fill:#BBDEFB
    style nz fill:#E1BEE7
    style n110 fill:#C8E6C9
    style ns fill:#FFE0B2
    style ny fill:#FFE0B2
    style n66 fill:#FFE0B2
    style n125 fill:#FFE0B2
    style n100 fill:#FFE0B2
    style n148 fill:#FFE0B2
    style s2 fill:#F8F8F8
    style n162 fill:#FFE0B2
    style n163 fill:#FFE0B2
    style n82 fill:#E1BEE7
    style n141 fill:#E1BEE7
    style n142 fill:#E1BEE7
    style n143 fill:#E1BEE7,stroke-width:4px,stroke-dasharray: 0
    style n88 fill:#FFE0B2
    style n89 fill:#FFE0B2
    style n36 fill:#FFE0B2
    style A fill:#FFFFFF
    style cli fill:#F8F8F8
    style activate fill:#F8F8F8
    style executive fill:#F8F8F8
    style s4 fill:transparent
