//! Kerberos credential creation

use std::sync::Arc;

use base64::Engine as _;
use libgssapi::context::{ClientCtx, CtxFlags};
use libgssapi::credential::{Cred, CredUsage};
use libgssapi::name::Name;
use libgssapi::oid::{GSS_MECH_KRB5, GSS_NT_HOSTBASED_SERVICE};
use tracing::debug;
use url::Url;

use crate::auth::{AuthContext, AuthError, AuthHeaderError, KerberosMaterial};

/// Create a Kerberos credential by resolving the principal from the ccache.
///
/// The GSSAPI `Cred` is acquired once and cached in the token generator
/// closure — it is `Clone` (Arc-wrapped) so each SPNEGO context gets a
/// cheap handle to the same underlying credential.
///
/// Returns `AuthContext::Kerberos(Some)` with a SPNEGO token generator on
/// success, or `AuthContext::Kerberos(None)` if the principal cannot be
/// resolved.
pub(super) fn kerberos_credential() -> AuthContext {
    match acquire_credential() {
        Ok((principal, cred)) => AuthContext::Kerberos(Some(KerberosMaterial {
            principal,
            generate_token: Arc::new(move |url: &Url| generate_spnego_token(&cred, url)),
        })),
        Err(e) => {
            tracing::warn!(error = %e, "Kerberos principal resolution failed");
            AuthContext::Kerberos(None)
        },
    }
}

/// Acquire GSSAPI credentials from the ccache and return the principal
/// name together with the `Cred` handle.
fn acquire_credential() -> Result<(String, Cred), AuthError> {
    let cred = Cred::acquire(None, None, CredUsage::Initiate, None).map_err(|e| {
        AuthError::NotAuthenticated(format!(
            "Kerberos ticket not available. Run `kinit` to authenticate. Error: {e:?}"
        ))
    })?;
    let name = cred.name().map_err(|e| {
        AuthError::NotAuthenticated(format!("Failed to get Kerberos principal name: {e:?}"))
    })?;
    let local = name
        .local_name(Some(&GSS_MECH_KRB5))
        .or_else(|_| name.display_name())
        .map_err(|e| {
            AuthError::NotAuthenticated(format!("Failed to resolve Kerberos local name: {e:?}"))
        })?;
    let principal = String::from_utf8_lossy(&local[..]).to_string();
    Ok((principal, cred))
}

/// Generate a SPNEGO token for the given URL using a cached `Cred`.
///
/// Each call creates a fresh `ClientCtx` (GSSAPI contexts are single-use)
/// but reuses the same credential handle.
fn generate_spnego_token(cred: &Cred, url: &Url) -> Result<String, AuthHeaderError> {
    let hostname = url
        .host_str()
        .ok_or_else(|| AuthHeaderError("No hostname in catalog URL".to_string()))?;

    let service_name = format!("HTTP@{}", hostname);
    debug!(service_principal = %service_name, "generating SPNEGO token");

    let target_name = Name::new(service_name.as_bytes(), Some(&GSS_NT_HOSTBASED_SERVICE))
        .map_err(|e| AuthHeaderError(format!("Failed to create GSSAPI name: {:?}", e)))?;

    let ctx_flags = CtxFlags::GSS_C_MUTUAL_FLAG | CtxFlags::GSS_C_REPLAY_FLAG;

    let mut client_ctx = ClientCtx::new(
        Some(cred.clone()),
        target_name,
        ctx_flags,
        Some(&GSS_MECH_KRB5),
    );

    let token = client_ctx
        .step(None, None)
        .map_err(|e| AuthHeaderError(format!("Kerberos context initialization failed: {:?}", e)))?;

    let token_bytes =
        token.ok_or_else(|| AuthHeaderError("No token generated by Kerberos".to_string()))?;

    let encoded_token = base64::engine::general_purpose::STANDARD.encode(&token_bytes[..]);
    debug!(token_bytes = token_bytes.len(), "generated SPNEGO token");

    Ok(encoded_token)
}
