# Renderer for the per-service configuration file consumed by the shared
# entry points in ../systemd/libexec. Both halves of this module produce one:
# the Services method from its own options, the Overrides method from the unit
# it is attached to.
{ lib }:

let
  inherit (lib)
    escapeShellArg
    escapeShellArgs
    optionalString
    ;

  bool = b: if b then "1" else "0";

in
{
  # `cfg` carries the union of what both methods can set; every field has a
  # default so each caller only supplies what applies to it.
  #
  # Argument lists are quoted twice: `escapeShellArgs` so each argument
  # survives the eval that expands them at the call site, and `escapeShellArg`
  # so the assignment itself survives being sourced.
  mkConf =
    {
      environment,
      unit,
      user ? "",
      group ? "",
      trustEnvironment ? false,
      execStart ? "",
      extraFloxArgs ? [ ],
      extraFloxActivateArgs ? [ ],
      extraFloxPullArgs ? [ ],
      pullAtServiceStart ? true,
      autoRestart ? false,
      floxHubTokenFile ? null,
      # pull.configs carries scheduling fields that belong to the timer, not
      # to the scripts.
      ...
    }:
    ''
      # Generated by the Flox NixOS module. Do not edit.
      FLOX_ENVIRONMENT=${escapeShellArg environment}
      FLOX_UNIT=${escapeShellArg unit}
      FLOX_USER=${escapeShellArg user}
      FLOX_GROUP=${escapeShellArg group}
      FLOX_TRUST=${bool trustEnvironment}
      FLOX_PULL_AT_SERVICE_START=${bool pullAtServiceStart}
      FLOX_AUTORESTART=${bool autoRestart}
      FLOX_ARGS=${escapeShellArg (escapeShellArgs extraFloxArgs)}
      FLOX_ACTIVATE_ARGS=${escapeShellArg (escapeShellArgs extraFloxActivateArgs)}
      FLOX_PULL_ARGS=${escapeShellArg (escapeShellArgs extraFloxPullArgs)}
      FLOX_EXEC_START=${escapeShellArg execStart}
    ''
    + optionalString (floxHubTokenFile != null) ''
      FLOX_TOKEN_FILE=${escapeShellArg (toString floxHubTokenFile)}
    '';

  # Every argument that has to survive being word-split out of a conf file.
  whitespaceSensitiveArgs =
    cfg:
    (cfg.extraFloxArgs or [ ]) ++ (cfg.extraFloxActivateArgs or [ ]) ++ (cfg.extraFloxPullArgs or [ ]);
}
