name: "BATS"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
  merge_group:

concurrency:
  group: "bats-${{ github.event.pull_request.event.number || github.sha }}"
  cancel-in-progress: true

jobs:
