# ============================================================================ #
#
#
#
# ---------------------------------------------------------------------------- #
#
name: "Flox Bash Tests"

on:
  push:
    branches:
      -  main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


# ---------------------------------------------------------------------------- #

jobs:
  flox-bash-tests:
    runs-on: ubuntu-latest
    env:
      SYSTEM: x86_64-linux
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
    - name: Install flox
      uses: flox/install-flox-action@v1.0.0

    - name: Git and SSH Setup
      run: |
        set -eu;
        set -o pipefail;
        mkdir -p /home/runner/.ssh;
        ssh-keyscan github.com >> /home/runner/.ssh/known_hosts;
        ssh-keygen -f /home/runner/.ssh/id_rsa -t rsa -N ''  \
                   -C gha@floxdev.com;
        chmod 600 /home/runner/.ssh/id_rsa;
        ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null;
        ssh-add /home/runner/.ssh/id_rsa;
        git config --global user.email "gha@floxdev.com";
        git config --global user.name "Flox GitHubActions";

    - uses: actions/checkout@v3

    - name: Show Env
      run: |
        set -eu;
        set -o pipefail;
        echo "# ============================================================================ #" >&2;
        { printf '    bash   version: '; bash --version|head -n1;      } >&2;
        { printf '    nix    version: '; nix  --version;               } >&2;
        { printf '    flox   version: '; flox --version|cut -d' ' -f2; } >&2;
        echo "# ---------------------------------------------------------------------------- #" >&2;

# ---------------------------------------------------------------------------- #

    - name: Build and Test
      run: |
        #set -eu;
        #set -o pipefail;
        # FIXME: we should be able to use strict mode for `flox print-dev-env;'
        pushd ./flox-bash;
        . <( flox print-dev-env '..#flox-bash'; );
        set -eu;
        set -o pipefail;
        make;
        make test;
        popd;


# ---------------------------------------------------------------------------- #
#
#
#
# ============================================================================ #
