# ============================================================================ #
#
# Run `pre-commit` over the codebase.
#
# ---------------------------------------------------------------------------- #

name: "Project Lints"
on:
  # Contrary to the ./ci.yml workflow,
  # this one is _not_ triggered by the `push` events
  # or `workflow_dispatch` invocations.
  # That is because `pre-commit` computes the diff between the current and the
  # target branch to skip the linting of unchanged files.
  # `push` and `workflow_dispatch` events do not provide this context.
  pull_request:
  merge_group:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

env:
  FLOX_DISABLE_METRICS: "true"

jobs:
  nix-git-hooks:
    name: "Nix Git Hooks"
    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Nix"
        uses: "./.github/actions/common-setup"
        with:
          GITHUB_ACCESS_TOKEN:    "${{ secrets.MANAGED_FLOXBOT_GITHUB_ACCESS_TOKEN_REPO_SCOPE }}"
          SUBSTITUTER:            "${{    vars.MANAGED_CACHE_PUBLIC_S3_BUCKET }}"
          SUBSTITUTER_KEY:        "${{ secrets.MANAGED_CACHE_PUBLIC_SECRET_KEY }}"
          AWS_ACCESS_KEY_ID:      "${{ secrets.MANAGED_CACHE_PUBLIC_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY:  "${{ secrets.MANAGED_CACHE_PUBLIC_AWS_SECRET_ACCESS_KEY }}"
          SSH_KEY:                "${{ secrets.MANAGED_FLOXBOT_SSH_KEY }}"



      - name: "Determine target branch ( PR )"
        if: ${{ github.event_name == 'pull_request' }}
        # Unlike `github.event.merge_group.base_ref`, `github.base_ref`
        # only includes the final ref name
        # prepend `refs/heads/` to match the format of
        # `github.event.merge_group.base_ref`.
        run: |
          echo 'TARGET_REF=refs/heads/${{ github.base_ref }}' >> "$GITHUB_ENV";
          echo 'HEAD_REF=refs/heads/${{ github.head_ref }}' >> "$GITHUB_ENV";

      - name: "Fetch target branch ( Merge Queue )"
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          echo 'TARGET_REF=${{ github.event.merge_group.base_ref }}' >> "$GITHUB_ENV";
          echo 'HEAD_REF=${{ github.event.merge_group.head_ref }}' >> "$GITHUB_ENV";

      - name: "Set merge queue flag"
        if : ${{ github.event_name == 'merge_group' }}
        run: |
          echo 'IS_MERGE_QUEUE=1' >> "$GITHUB_ENV";

      # Fetch the head and target branch and create a local reference to it.
      # Apparently git does not like fetching into the current branch,
      # so we fetch into temporary branches `target` and `head`.
      - name: "Fetch branches"
        run: |
          git fetch --atomic origin \
            "$TARGET_REF:target" \
            "$HEAD_REF:head";

      # avoid the next step being filled with nix substitution logs
      # and ensure that `pre-commit` can run cargo with the `--offline` flag
      - name: "Fetch rust dependencies"
        run: |
          nix develop -L --no-update-lock-file --command \
            cargo fetch \
            --manifest-path ./cli/Cargo.toml \
            --locked;

      # Run pre-commit hooks on the diff between the target branch and HEAD.
      # The target branch and HEAD are resolved to a revision using
      # `git rev-parse`.
      - name: "Run Nix Git Hooks"
        run: |
          echo "IS_MERGE_QUEUE: $IS_MERGE_QUEUE"
          echo "TARGET_REF: $TARGET_REF ($( git rev-parse "target" ))"
          echo "HEAD_REF: $HEAD_REF ($( git rev-parse "head" ))"

          nix develop -L --no-update-lock-file --command \
            pre-commit run \
              --verbose \
              --hook-stage manual \
              --from-ref "$( git rev-parse "target" )" \
              --to-ref   "$( git rev-parse "head" )";

# ---------------------------------------------------------------------------- #
#
#
#
# ============================================================================ #
