name: "!IGNORE! Proxy Build CI"

on:
  push:
  workflow_dispatch:

env:
  NIX_REMOTE_BUILDER: "ssh-ng://nixbld@build-proxy.floxdev.com"
  NIX_FLAKE_URL: "."

jobs:
  build:
    strategy:
      matrix:
        system: ["x86_64-darwin", "aarch64-darwin", "x86_64-linux", "aarch64-linux"]

    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v4"
      - uses: "nixbuild/nix-quick-install-action@v28"

      - name: "setup ssh"
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.MANAGED_FLOXBOT_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 0400 ~/.ssh/id_ed25519
          echo "build-proxy.floxdev.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMk7W4OR6g/7kXyXv5+vHkm50zux/s+ww/Y8LUBac3VC" > ~/.ssh/known_hosts

      - name: "flox build"
        run: |
          nix build \
            ${{ env.NIX_FLAKE_URL }}#.packages.${{ matrix.system }}.{flox,flox-cli,flox-pkgdb,flox-cli-tests} \
            --print-out-paths  \
            --no-link \
            --print-build-logs \
            --eval-store auto \
            --store "$NIX_REMOTE_BUILDER"
